sudo: false

before_install:
  - gem update --system
  - gem install bundler

script: bundle exec rake spec_with_coveralls

matrix:
  include:
    - rvm: 2.3.0
      gemfile: Gemfile
    - rvm: 2.4.0
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: gemfiles/jruby.gemfile
